# 模板引擎目录
viewpath: /home/www/templates/
# MySQL数据库配置
database:
    default:
        - host:     127.0.0.1
          port:     3306
          user:     root
          pass:     "8692651"
          name:     test
          type:     mysql
          role:     master
          charset:  utf8
          priority: 1
        - host:     127.0.0.1
          port:     3306
          user:     root
          pass:     "8692651"
          name:     test
          type:     mysql
          role:     master
          charset:  utf8
          priority: 1
# Redis数据库配置
redis:
    default: 127.0.0.1:6379,0
    cache  : 127.0.0.1:6379,2
