# 监控服务主动拉取监控数据配置
[active-pulling]
    # 业务类别 腾讯问诊 订单总数
    [[active-pulling.tencent-inquiry]]
        groupId    = 3533761
        metricName = "OrderCount"                                  # 监控项名称
        url        = "http://ylt.medlinker.com/monitor/ordercount" # 监控数据地址
        interval   = "1m"                                          # d:日 h:小时 m:分 s:秒
    # 业务类别 腾讯问诊 超时订单总数
    [[active-pulling.tencent-inquiry]]
        groupId    = 3533711
        metricName = "TimedOutOrderCount"
        url        = "http://ylt.medlinker.com/monitor/timedout-ordercount"
        interval   = "1m"